---
Fake Internal error:
  content:
    addon_data:
      Core::Path:
        class: SL_Path_Addon
        content:
        - class: Root
          data:
            href: /
            label: Test facility
          type: Link
        type: Container
    object_data:
      t1:
        class: SL_Object SL_Error_Internal
        content:
        - class: SL_Dialog
          content:
          - class: Message
            content:
            - data:
                label: 'Request can not be completed, due to unexpected difficulties.
                  Please try again. (Error: Internal).'
              type: Label
            type: Container
          - class: Buttons
            content: []
            type: Container
          type: Container
        type: Container
    object_order:
    - t1
    template: Default
  mime_type: ~
  response: CONTENT
